---
- name: Install Unzip, Apache2, mariadb, php, Wordpress and Nginx
  hosts: all
  become: yes
  tasks:
    - name: Install tar
      dnf:
        name: tar
        state: present
        update_cache: yes
      register: tar

    - name: Install unzip
      dnf:
        name: unzip
        state: present
        update_cache: yes
      register: unzip
             
    - name: Install Apache2
      dnf:
        name: httpd
        state: present
        update_cache: yes
      register: apache2
      notify: Restart Apache2

    - name: Install mariadb
      dnf:
        name: mariadb-server
        state: present
        update_cache: yes
      register: mariadb
      notify: Restart mariadb

    - name: Install php
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - php
        - php-mysqlnd
        - php-curl
        - php-gd
        - php-mbstring
        - php-xml
        - php-xmlrpc
        - php-soap
        - php-intl
      register: php
      notify: Restart Apache2

    - name: Install Wordpress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html
        remote_src: yes
      register: wordpress

    - name: Configure Wordpress
      template:
        src: wp-config.php
        dest: /var/www/html/wordpress/wp-config.php      
      register: wp_config

    - name: Install Nginx
      dnf:
        name: nginx
        state: present
        update_cache: yes
      register: nginx
      notify: Restart Nginx

    - name: Configure Nginx
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      register: nginx_config
      notify: Restart Nginx

    - name: Configure Apache2
      template:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      register: nginx_config
      notify: Restart Nginx


  handlers:
    - name: Restart Apache2
      service:
        name: httpd
        state: restarted

    - name: Restart mariadb
      service:
        name: mariadb
        state: restarted

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Stop and disable firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: no
