version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wppass
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

  php:
    image: php:7.4-apache
    container_name: php-container
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wppass
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-data:/var/www/html
    expose:
      - 80
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    depends_on:
      - php
    volumes:
      - wordpress-data:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-container
    depends_on:
      - php
    volumes:
      - nginx-conf:/etc/nginx/conf.d
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  mariadb-data:
  wordpress-data:
  nginx-conf:
